"""Mapa de nombres de LAE oficiales a nombres en BD quiniela."""
LAE_TO_BD = {
    "Alavés": "alaves",
    "Alavés B": "alaves",
    "Getafe B": "getafe",
    "Getafe": "getafe",
    "Sevilla Ath.": "sevilla",
    "Sevilla": "sevilla",
    "Rayo Vallecano": "vallecano",
    "Racing De Santander": "santander",
    "Racing Santander": "santander",
    "Villarreal B": "villarreal",
    "Villarreal": "villarreal",
    "Espanyol B": "espanol",
    "Espanyol": "espanol",
    "Levante B": "levante",
    "Levante": "levante",
    "R.C. Celta B": "celta",
    "R.C. Celta": "celta",
    "Celta": "celta",
    "Osasuna B": "osasuna",
    "Osasuna": "osasuna",
    "Andorra": "andorra",
    "Ceuta": "ceuta",
    "Cádiz": "cadiz",
    "Cadiz": "cadiz",
    "Fortuna Sittard": None,  # no en BD
    "R. Oviedo": "oviedo",
    "R.Oviedo": "oviedo",
    "Oviedo": "oviedo",
    "Granada Femenino": "granada",
    "Granada": "granada",
    "Mallorca B": "mallorca",
    "Mallorca": "mallorca",
    "Valladolid B": "valladolid",
    "Valladolid": "valladolid",
    "Eibar Femenino": "eibar",
    "Eibar": "eibar",
    "Tenerife B": None,  # no en BD
    "Burgos": "burgos",
    "Córdoba": "cordoba",
    "Cordoba": "cordoba",
    "Girona": "girona",
    "Leganés": "leganes",
    "Leganes": "leganes",
    "Las Palmas B": "las_palmas",
    "Las Palmas": "las_palmas",
    "Albacete": "albacete",
    "Sporting B": "sp_gijon",
    "Sporting": "sp_gijon",
    "Sabadell": None,  # no en BD
    "Deportivo B": "la_coruna",
    "Deportivo": "la_coruna",
    "Elche": "elche",
    "Almería": "almeria",
    "Almeria": "almeria",
    "Castellón": "castellon",
    "Castellon": "castellon",
    "Real Madrid": "real_madrid",
    "Athletic Bilbao": "ath_bilbao",
    "Ath Bilbao": "ath_bilbao",
    "Atlético Madrid": "ath_madrid",
    "Ath Madrid": "ath_madrid",
    "Atlético de Madrid": "ath_madrid",
    "Real Sociedad": "sociedad",
    "Sociedad": "sociedad",
    "Real Zaragoza": "zaragoza",
    "Zaragoza": "zaragoza",
    "Huesca": "huesca",
    "Málaga": "malaga",
    "Malaga": "malaga",
    "Mirandés": "mirandes",
    "Mirandes": "mirandes",
    "Cultural Leonesa": "cultural_leonesa",
}


def normalize(lae_name):
    """Devuelve el nombre en BD o None si no está."""
    return LAE_TO_BD.get(lae_name.strip().rstrip(".")) or LAE_TO_BD.get(lae_name)
